---
version: "3.3"
services:
    fsg-scores:
        image: fsg-scores:latest
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:80
